# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c33aa45766d936eef04d531b37c2639db933c0be198223f2b1411c3265fb1a9c0848119d924b62d430e381099a25323fae28563d0b5601e4a4e3422f300e1aa6

test:
  secret_key_base: c75c5ba07c81c3985581ac873338161c4e2c747d22fb3ad7fe4876b6f4647b572d4b68c53a120d55bc8e0825be7a5d425eb7edbf8186273b37fe9f2668d46a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
